CREATE DATABASE IF NOT EXISTS namedb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE namedb;

CREATE TABLE IF NOT EXISTS names (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);
